-dontwarn org.apache.sshd.**
-keep class com.kisshkitty.** { *; }
-keep class * extends androidx.room.RoomDatabase
-keep class net.schmizz.sshj.** { *; }
-keep class org.bouncycastle.** { *; }
-dontwarn net.schmizz.sshj.**
-dontwarn org.bouncycastle.**
-dontwarn sun.security.x509.**
-dontwarn sun.security.ssl.**
-dontwarn net.i2p.crypto.eddsa.**
-dontwarn javax.security.auth.**
