-dontwarn org.apache.sshd.**
-keep class com.kisshkitty.** { *; }
-keep class * extends androidx.room.RoomDatabase
-keep class net.schmizz.sshj.** { *; }
-keep class org.bouncycastle.** { *; }
-dontwarn net.schmizz.sshj.**
-dontwarn org.bouncycastle.**
